### ISSUE TITLE
I can not build the graph path

### ISSUE THREAD

**Issue by HosoyaKenn** [NobleMathews/mocktail-blend#1]
When I run python3 pipeline.py , it reminds me there is no path .What's the problem

**Comment by HosoyaKenn** [comment]
in extract_paths.py 
extract_ast_paths
try: ast = nx.DiGraph(nx.drawing.nx_agraph.read_dot(ast_path)) 
no reaction and turn to except so there is no ast
how can i fix it?
![Screenshot from 2023-03-01 22-00-24](https://user-images.githubusercontent.com/62983214/222162563-c8eb97ef-d41a-4a7f-bd08-9e1b44b4a427.png)

**Comment by NobleMathews** [comment]
Hi, what is the exception you are running into? 
It's hard to debug with only this, could you change the try-except logic to:

```
except Exception as e: 
        print(e)
```

**Comment by HosoyaKenn** [comment]
thank u for reply , I have found my mistake , I didn't install pygraphviz
